#pragma once

#define MAKE_ERROR_CODE(ERROR_SHIFT, ERROR_CATEGORY, ERROR_CODE)	(ERROR_CODE << ERROR_SHIFT) & ERROR_CATEGORY
#define MAKE_ERROR(TYPE, ERROR_CODE)								MAKE_ERROR_CODE(ERROR_SHIFT_##TYPE, ERROR_CATEGORY_##TYPE, ERROR_CODE)

#define ERROR_SHIFT_SYSTEM											0x00000000
#define ERROR_CATEGORY_SYSTEM										0x000000FF
#define MONITOR_INFORMATION_ERROR									MAKE_ERROR(SYSTEM, 1)

#define ERROR_SHIFT_D3D12											0x00000010
#define ERROR_CATEGORY_D3D12										0x0000FF00
#define CREATE_DXGI_FACTORY_FAILED									MAKE_ERROR(D3D12, 1)
#define CREATE_DEVICE_FAILED										MAKE_ERROR(D3D12, 2)
#define CREATE_COMMAND_QUEUE_FAILED									MAKE_ERROR(D3D12, 3)
#define CREATE_SWAP_CHAIN_FAILED									MAKE_ERROR(D3D12, 4)
#define CREATE_HEAP_DESCRIPTOR_FAILED								MAKE_ERROR(D3D12, 5)
#define CREATE_COMMAND_ALLOCATOR_FAILED								MAKE_ERROR(D3D12, 6)
#define CREATE_ROOT_SIGNATURE_FAILED								MAKE_ERROR(D3D12, 7)
#define CREATE_SHADER_FAILED										MAKE_ERROR(D3D12, 8)
#define CREATE_PSO_FAILED											MAKE_ERROR(D3D12, 9)
#define CREATE_COMMAND_LIST_FAILED									MAKE_ERROR(D3D12, 10)
#define CREATE_COMMITTED_RESOURCE_FAILED							MAKE_ERROR(D3D12, 11)
#define CREATE_FENCE_FAILED											MAKE_ERROR(D3D12, 12)
#define GET_WARP_ADAPTER_FAILED										MAKE_ERROR(D3D12, 13)
#define GET_BUFFER_FROM_SWAPCHAIN_FAILED							MAKE_ERROR(D3D12, 14)
#define CLOSE_COMMAND_LIST_FAILED									MAKE_ERROR(D3D12, 15)
#define MAP_RESOURCE_FAILED											MAKE_ERROR(D3D12, 16)
#define WAIT_FOR_PREV_FRAME_FAILED									MAKE_ERROR(D3D12, 17)
#define SWAPCHAIIN_PRESENT_FAILED									MAKE_ERROR(D3D12, 18)
#define RESET_COMMAND_FAILED										MAKE_ERROR(D3D12, 19)
#define CHECK_FEATURE_SUPPORT_FAILED								MAKE_ERROR(D3D12, 20)